---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Pages
  create: all
  match: "*.md"
  exclude: "*README.md"
  new_doc_ext: md
  templates:
  - landing-page
  - html-content
  - startpage
- type: directory
  path: _banners
  label: Banners
  create: all
  match: "*.md"
  new_doc_ext: md
  templates:
  - fullsize-banner
- type: directory
  path: _products
  label: Produkte
  create: all
  match: "*.md"
  new_doc_ext: md
  templates:
  - produkt
- type: directory
  path: _textbanner
  label: Textbanner
  create: all
  match: "*.md"
  new_doc_ext: md
  templates:
  - text-banner
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
