---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Einstiegsseiten
  create: all
  match: "*.md"
  exclude: "*README.md"
  new_doc_ext: md
  templates:
  - landing-page
  - html-content
  - startpage
- type: directory
  path: _banners
  label: Banner
  create: all
  match: "*.md"
  new_doc_ext: md
  templates:
  - fullsize-banner
- type: directory
  path: _products
  label: Produkte
  create: all
  match: "*.md"
  new_doc_ext: md
  templates:
  - produkt
- type: directory
  path: _textbanner
  label: Textbanner
  create: all
  match: "*.md"
  new_doc_ext: md
  templates:
  - text-banner
- type: directory
  path: _creation
  label: Erstellung
  create: all
  match: "*.md"
  new_doc_ext: md
  templates:
  - creation
- type: directory
  path: _instagram
  label: Instagram
  create: all
  match: "*.md"
  new_doc_ext: md
  templates:
  - instagram
- type: directory
  path: _events
  label: Events
  create: all
  match: "*.md"
  new_doc_ext: md
  templates:
    - events
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
